// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/core.proto

package com.akaxin.zaly.proto;

public final class CoreProto {
  private CoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code core.HeaderKey}
   */
  public enum HeaderKey
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *0-500 分配给CLIENT
     * </pre>
     *
     * <code>CLIENT_VERSION = 0;</code>
     */
    CLIENT_VERSION(0),
    /**
     * <code>CLIENT_SESSION_ID = 1;</code>
     */
    CLIENT_SESSION_ID(1),
    /**
     * <pre>
     * 客户端正在使用的语言, cn/en
     * </pre>
     *
     * <code>CLIENT_LANGUAGE = 2;</code>
     */
    CLIENT_LANGUAGE(2),
    /**
     * <code>CLIENT_SOCKET_TYPE = 3;</code>
     */
    CLIENT_SOCKET_TYPE(3),
    /**
     * <pre>
     *501-1000 分配给CLIENT_REQUEST
     * </pre>
     *
     * <code>CLIENT_REQUEST_REFERER = 501;</code>
     */
    CLIENT_REQUEST_REFERER(501),
    /**
     * <pre>
     *客户端访问的服务host
     * </pre>
     *
     * <code>CLIENT_REQUEST_SERVER_HOST = 502;</code>
     */
    CLIENT_REQUEST_SERVER_HOST(502),
    /**
     * <pre>
     *客户端访问的服务port
     * </pre>
     *
     * <code>CLIENT_REQUEST_SERVER_PORT = 503;</code>
     */
    CLIENT_REQUEST_SERVER_PORT(503),
    /**
     * <pre>
     *1001-2000 分配给SERVER
     * </pre>
     *
     * <code>SERVER_VERSION = 1001;</code>
     */
    SERVER_VERSION(1001),
    /**
     * <pre>
     *服务端host
     * </pre>
     *
     * <code>SERVER_HOST = 1002;</code>
     */
    SERVER_HOST(1002),
    /**
     * <pre>
     *服务端port
     * </pre>
     *
     * <code>SERVER_PORT = 1003;</code>
     */
    SERVER_PORT(1003),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *0-500 分配给CLIENT
     * </pre>
     *
     * <code>CLIENT_VERSION = 0;</code>
     */
    public static final int CLIENT_VERSION_VALUE = 0;
    /**
     * <code>CLIENT_SESSION_ID = 1;</code>
     */
    public static final int CLIENT_SESSION_ID_VALUE = 1;
    /**
     * <pre>
     * 客户端正在使用的语言, cn/en
     * </pre>
     *
     * <code>CLIENT_LANGUAGE = 2;</code>
     */
    public static final int CLIENT_LANGUAGE_VALUE = 2;
    /**
     * <code>CLIENT_SOCKET_TYPE = 3;</code>
     */
    public static final int CLIENT_SOCKET_TYPE_VALUE = 3;
    /**
     * <pre>
     *501-1000 分配给CLIENT_REQUEST
     * </pre>
     *
     * <code>CLIENT_REQUEST_REFERER = 501;</code>
     */
    public static final int CLIENT_REQUEST_REFERER_VALUE = 501;
    /**
     * <pre>
     *客户端访问的服务host
     * </pre>
     *
     * <code>CLIENT_REQUEST_SERVER_HOST = 502;</code>
     */
    public static final int CLIENT_REQUEST_SERVER_HOST_VALUE = 502;
    /**
     * <pre>
     *客户端访问的服务port
     * </pre>
     *
     * <code>CLIENT_REQUEST_SERVER_PORT = 503;</code>
     */
    public static final int CLIENT_REQUEST_SERVER_PORT_VALUE = 503;
    /**
     * <pre>
     *1001-2000 分配给SERVER
     * </pre>
     *
     * <code>SERVER_VERSION = 1001;</code>
     */
    public static final int SERVER_VERSION_VALUE = 1001;
    /**
     * <pre>
     *服务端host
     * </pre>
     *
     * <code>SERVER_HOST = 1002;</code>
     */
    public static final int SERVER_HOST_VALUE = 1002;
    /**
     * <pre>
     *服务端port
     * </pre>
     *
     * <code>SERVER_PORT = 1003;</code>
     */
    public static final int SERVER_PORT_VALUE = 1003;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HeaderKey valueOf(int value) {
      return forNumber(value);
    }

    public static HeaderKey forNumber(int value) {
      switch (value) {
        case 0: return CLIENT_VERSION;
        case 1: return CLIENT_SESSION_ID;
        case 2: return CLIENT_LANGUAGE;
        case 3: return CLIENT_SOCKET_TYPE;
        case 501: return CLIENT_REQUEST_REFERER;
        case 502: return CLIENT_REQUEST_SERVER_HOST;
        case 503: return CLIENT_REQUEST_SERVER_PORT;
        case 1001: return SERVER_VERSION;
        case 1002: return SERVER_HOST;
        case 1003: return SERVER_PORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HeaderKey>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HeaderKey> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeaderKey>() {
            public HeaderKey findValueByNumber(int number) {
              return HeaderKey.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.akaxin.zaly.proto.CoreProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final HeaderKey[] VALUES = values();

    public static HeaderKey valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HeaderKey(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.HeaderKey)
  }

  public interface ErrorInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.ErrorInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string code = 1;</code>
     */
    java.lang.String getCode();
    /**
     * <code>string code = 1;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>string info = 2;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>string info = 2;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * <pre>
   *请求的Errinfo
   * </pre>
   *
   * Protobuf type {@code core.ErrorInfo}
   */
  public  static final class ErrorInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.ErrorInfo)
      ErrorInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorInfo.newBuilder() to construct.
    private ErrorInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorInfo() {
      code_ = "";
      info_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              info_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.zaly.proto.CoreProto.internal_static_core_ErrorInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.zaly.proto.CoreProto.internal_static_core_ErrorInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.zaly.proto.CoreProto.ErrorInfo.class, com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object code_;
    /**
     * <code>string code = 1;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object info_;
    /**
     * <code>string info = 2;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <code>string info = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
      }
      if (!getInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, info_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
      }
      if (!getInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, info_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.zaly.proto.CoreProto.ErrorInfo)) {
        return super.equals(obj);
      }
      com.akaxin.zaly.proto.CoreProto.ErrorInfo other = (com.akaxin.zaly.proto.CoreProto.ErrorInfo) obj;

      boolean result = true;
      result = result && getCode()
          .equals(other.getCode());
      result = result && getInfo()
          .equals(other.getInfo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.zaly.proto.CoreProto.ErrorInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求的Errinfo
     * </pre>
     *
     * Protobuf type {@code core.ErrorInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.ErrorInfo)
        com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.zaly.proto.CoreProto.internal_static_core_ErrorInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.zaly.proto.CoreProto.internal_static_core_ErrorInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.zaly.proto.CoreProto.ErrorInfo.class, com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder.class);
      }

      // Construct using com.akaxin.zaly.proto.CoreProto.ErrorInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = "";

        info_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.zaly.proto.CoreProto.internal_static_core_ErrorInfo_descriptor;
      }

      public com.akaxin.zaly.proto.CoreProto.ErrorInfo getDefaultInstanceForType() {
        return com.akaxin.zaly.proto.CoreProto.ErrorInfo.getDefaultInstance();
      }

      public com.akaxin.zaly.proto.CoreProto.ErrorInfo build() {
        com.akaxin.zaly.proto.CoreProto.ErrorInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.zaly.proto.CoreProto.ErrorInfo buildPartial() {
        com.akaxin.zaly.proto.CoreProto.ErrorInfo result = new com.akaxin.zaly.proto.CoreProto.ErrorInfo(this);
        result.code_ = code_;
        result.info_ = info_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.zaly.proto.CoreProto.ErrorInfo) {
          return mergeFrom((com.akaxin.zaly.proto.CoreProto.ErrorInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.zaly.proto.CoreProto.ErrorInfo other) {
        if (other == com.akaxin.zaly.proto.CoreProto.ErrorInfo.getDefaultInstance()) return this;
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (!other.getInfo().isEmpty()) {
          info_ = other.info_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.zaly.proto.CoreProto.ErrorInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.zaly.proto.CoreProto.ErrorInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 1;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 1;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>string code = 1;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>string info = 2;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string info = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string info = 2;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string info = 2;</code>
       */
      public Builder clearInfo() {
        
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string info = 2;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        info_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.ErrorInfo)
    }

    // @@protoc_insertion_point(class_scope:core.ErrorInfo)
    private static final com.akaxin.zaly.proto.CoreProto.ErrorInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.zaly.proto.CoreProto.ErrorInfo();
    }

    public static com.akaxin.zaly.proto.CoreProto.ErrorInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorInfo>
        PARSER = new com.google.protobuf.AbstractParser<ErrorInfo>() {
      public ErrorInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorInfo> getParserForType() {
      return PARSER;
    }

    public com.akaxin.zaly.proto.CoreProto.ErrorInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransportPackageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.TransportPackageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */
    int getHeaderCount();
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */
    boolean containsHeader(
        int key);
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getHeader();
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getHeaderMap();
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */

    java.lang.String getHeaderOrDefault(
        int key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */

    java.lang.String getHeaderOrThrow(
        int key);

    /**
     * <pre>
     *body
     * </pre>
     *
     * <code>bytes body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <pre>
     *errInfo
     * </pre>
     *
     * <code>.core.ErrorInfo err = 3;</code>
     */
    boolean hasErr();
    /**
     * <pre>
     *errInfo
     * </pre>
     *
     * <code>.core.ErrorInfo err = 3;</code>
     */
    com.akaxin.zaly.proto.CoreProto.ErrorInfo getErr();
    /**
     * <pre>
     *errInfo
     * </pre>
     *
     * <code>.core.ErrorInfo err = 3;</code>
     */
    com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder getErrOrBuilder();
  }
  /**
   * <pre>
   *传输的数据体
   * </pre>
   *
   * Protobuf type {@code core.TransportPackageData}
   */
  public  static final class TransportPackageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.TransportPackageData)
      TransportPackageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportPackageData.newBuilder() to construct.
    private TransportPackageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportPackageData() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransportPackageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                header_ = com.google.protobuf.MapField.newMapField(
                    HeaderDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              header__ = input.readMessage(
                  HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              header_.getMutableMap().put(
                  header__.getKey(), header__.getValue());
              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            }
            case 26: {
              com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder subBuilder = null;
              if (err_ != null) {
                subBuilder = err_.toBuilder();
              }
              err_ = input.readMessage(com.akaxin.zaly.proto.CoreProto.ErrorInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(err_);
                err_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.zaly.proto.CoreProto.internal_static_core_TransportPackageData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.zaly.proto.CoreProto.internal_static_core_TransportPackageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.zaly.proto.CoreProto.TransportPackageData.class, com.akaxin.zaly.proto.CoreProto.TransportPackageData.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private static final class HeaderDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  com.akaxin.zaly.proto.CoreProto.internal_static_core_TransportPackageData_HeaderEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> header_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetHeader() {
      if (header_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      return header_;
    }

    public int getHeaderCount() {
      return internalGetHeader().getMap().size();
    }
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */

    public boolean containsHeader(
        int key) {
      
      return internalGetHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getHeader() {
      return getHeaderMap();
    }
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getHeaderMap() {
      return internalGetHeader().getMap();
    }
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */

    public java.lang.String getHeaderOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *header
     * </pre>
     *
     * <code>map&lt;int32, string&gt; header = 1;</code>
     */

    public java.lang.String getHeaderOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetHeader().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     *body
     * </pre>
     *
     * <code>bytes body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int ERR_FIELD_NUMBER = 3;
    private com.akaxin.zaly.proto.CoreProto.ErrorInfo err_;
    /**
     * <pre>
     *errInfo
     * </pre>
     *
     * <code>.core.ErrorInfo err = 3;</code>
     */
    public boolean hasErr() {
      return err_ != null;
    }
    /**
     * <pre>
     *errInfo
     * </pre>
     *
     * <code>.core.ErrorInfo err = 3;</code>
     */
    public com.akaxin.zaly.proto.CoreProto.ErrorInfo getErr() {
      return err_ == null ? com.akaxin.zaly.proto.CoreProto.ErrorInfo.getDefaultInstance() : err_;
    }
    /**
     * <pre>
     *errInfo
     * </pre>
     *
     * <code>.core.ErrorInfo err = 3;</code>
     */
    public com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder getErrOrBuilder() {
      return getErr();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetHeader(),
          HeaderDefaultEntryHolder.defaultEntry,
          1);
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      if (err_ != null) {
        output.writeMessage(3, getErr());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetHeader().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, header__);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      if (err_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getErr());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.zaly.proto.CoreProto.TransportPackageData)) {
        return super.equals(obj);
      }
      com.akaxin.zaly.proto.CoreProto.TransportPackageData other = (com.akaxin.zaly.proto.CoreProto.TransportPackageData) obj;

      boolean result = true;
      result = result && internalGetHeader().equals(
          other.internalGetHeader());
      result = result && getBody()
          .equals(other.getBody());
      result = result && (hasErr() == other.hasErr());
      if (hasErr()) {
        result = result && getErr()
            .equals(other.getErr());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetHeader().getMap().isEmpty()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeader().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      if (hasErr()) {
        hash = (37 * hash) + ERR_FIELD_NUMBER;
        hash = (53 * hash) + getErr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.zaly.proto.CoreProto.TransportPackageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *传输的数据体
     * </pre>
     *
     * Protobuf type {@code core.TransportPackageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.TransportPackageData)
        com.akaxin.zaly.proto.CoreProto.TransportPackageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.zaly.proto.CoreProto.internal_static_core_TransportPackageData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetHeader();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableHeader();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.zaly.proto.CoreProto.internal_static_core_TransportPackageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.zaly.proto.CoreProto.TransportPackageData.class, com.akaxin.zaly.proto.CoreProto.TransportPackageData.Builder.class);
      }

      // Construct using com.akaxin.zaly.proto.CoreProto.TransportPackageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableHeader().clear();
        body_ = com.google.protobuf.ByteString.EMPTY;

        if (errBuilder_ == null) {
          err_ = null;
        } else {
          err_ = null;
          errBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.zaly.proto.CoreProto.internal_static_core_TransportPackageData_descriptor;
      }

      public com.akaxin.zaly.proto.CoreProto.TransportPackageData getDefaultInstanceForType() {
        return com.akaxin.zaly.proto.CoreProto.TransportPackageData.getDefaultInstance();
      }

      public com.akaxin.zaly.proto.CoreProto.TransportPackageData build() {
        com.akaxin.zaly.proto.CoreProto.TransportPackageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.zaly.proto.CoreProto.TransportPackageData buildPartial() {
        com.akaxin.zaly.proto.CoreProto.TransportPackageData result = new com.akaxin.zaly.proto.CoreProto.TransportPackageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.header_ = internalGetHeader();
        result.header_.makeImmutable();
        result.body_ = body_;
        if (errBuilder_ == null) {
          result.err_ = err_;
        } else {
          result.err_ = errBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.zaly.proto.CoreProto.TransportPackageData) {
          return mergeFrom((com.akaxin.zaly.proto.CoreProto.TransportPackageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.zaly.proto.CoreProto.TransportPackageData other) {
        if (other == com.akaxin.zaly.proto.CoreProto.TransportPackageData.getDefaultInstance()) return this;
        internalGetMutableHeader().mergeFrom(
            other.internalGetHeader());
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        if (other.hasErr()) {
          mergeErr(other.getErr());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.zaly.proto.CoreProto.TransportPackageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.zaly.proto.CoreProto.TransportPackageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> header_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetHeader() {
        if (header_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        return header_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableHeader() {
        onChanged();;
        if (header_ == null) {
          header_ = com.google.protobuf.MapField.newMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        if (!header_.isMutable()) {
          header_ = header_.copy();
        }
        return header_;
      }

      public int getHeaderCount() {
        return internalGetHeader().getMap().size();
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */

      public boolean containsHeader(
          int key) {
        
        return internalGetHeader().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeaderMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getHeader() {
        return getHeaderMap();
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.String> getHeaderMap() {
        return internalGetHeader().getMap();
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */

      public java.lang.String getHeaderOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetHeader().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */

      public java.lang.String getHeaderOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetHeader().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeader() {
        internalGetMutableHeader().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */

      public Builder removeHeader(
          int key) {
        
        internalGetMutableHeader().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableHeader() {
        return internalGetMutableHeader().getMutableMap();
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */
      public Builder putHeader(
          int key,
          java.lang.String value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *header
       * </pre>
       *
       * <code>map&lt;int32, string&gt; header = 1;</code>
       */

      public Builder putAllHeader(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableHeader().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *body
       * </pre>
       *
       * <code>bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       *body
       * </pre>
       *
       * <code>bytes body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *body
       * </pre>
       *
       * <code>bytes body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      private com.akaxin.zaly.proto.CoreProto.ErrorInfo err_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.akaxin.zaly.proto.CoreProto.ErrorInfo, com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder, com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder> errBuilder_;
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public boolean hasErr() {
        return errBuilder_ != null || err_ != null;
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public com.akaxin.zaly.proto.CoreProto.ErrorInfo getErr() {
        if (errBuilder_ == null) {
          return err_ == null ? com.akaxin.zaly.proto.CoreProto.ErrorInfo.getDefaultInstance() : err_;
        } else {
          return errBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public Builder setErr(com.akaxin.zaly.proto.CoreProto.ErrorInfo value) {
        if (errBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          err_ = value;
          onChanged();
        } else {
          errBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public Builder setErr(
          com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder builderForValue) {
        if (errBuilder_ == null) {
          err_ = builderForValue.build();
          onChanged();
        } else {
          errBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public Builder mergeErr(com.akaxin.zaly.proto.CoreProto.ErrorInfo value) {
        if (errBuilder_ == null) {
          if (err_ != null) {
            err_ =
              com.akaxin.zaly.proto.CoreProto.ErrorInfo.newBuilder(err_).mergeFrom(value).buildPartial();
          } else {
            err_ = value;
          }
          onChanged();
        } else {
          errBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public Builder clearErr() {
        if (errBuilder_ == null) {
          err_ = null;
          onChanged();
        } else {
          err_ = null;
          errBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder getErrBuilder() {
        
        onChanged();
        return getErrFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      public com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder getErrOrBuilder() {
        if (errBuilder_ != null) {
          return errBuilder_.getMessageOrBuilder();
        } else {
          return err_ == null ?
              com.akaxin.zaly.proto.CoreProto.ErrorInfo.getDefaultInstance() : err_;
        }
      }
      /**
       * <pre>
       *errInfo
       * </pre>
       *
       * <code>.core.ErrorInfo err = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.akaxin.zaly.proto.CoreProto.ErrorInfo, com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder, com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder> 
          getErrFieldBuilder() {
        if (errBuilder_ == null) {
          errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.akaxin.zaly.proto.CoreProto.ErrorInfo, com.akaxin.zaly.proto.CoreProto.ErrorInfo.Builder, com.akaxin.zaly.proto.CoreProto.ErrorInfoOrBuilder>(
                  getErr(),
                  getParentForChildren(),
                  isClean());
          err_ = null;
        }
        return errBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.TransportPackageData)
    }

    // @@protoc_insertion_point(class_scope:core.TransportPackageData)
    private static final com.akaxin.zaly.proto.CoreProto.TransportPackageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.zaly.proto.CoreProto.TransportPackageData();
    }

    public static com.akaxin.zaly.proto.CoreProto.TransportPackageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportPackageData>
        PARSER = new com.google.protobuf.AbstractParser<TransportPackageData>() {
      public TransportPackageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransportPackageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransportPackageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportPackageData> getParserForType() {
      return PARSER;
    }

    public com.akaxin.zaly.proto.CoreProto.TransportPackageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_ErrorInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_ErrorInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_TransportPackageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_TransportPackageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_TransportPackageData_HeaderEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_TransportPackageData_HeaderEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017core/core.proto\022\004core\"\'\n\tErrorInfo\022\014\n\004" +
      "code\030\001 \001(\t\022\014\n\004info\030\002 \001(\t\"\251\001\n\024TransportPa" +
      "ckageData\0226\n\006header\030\001 \003(\0132&.core.Transpo" +
      "rtPackageData.HeaderEntry\022\014\n\004body\030\002 \001(\014\022" +
      "\034\n\003err\030\003 \001(\0132\017.core.ErrorInfo\032-\n\013HeaderE" +
      "ntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001*\373\001\n" +
      "\tHeaderKey\022\022\n\016CLIENT_VERSION\020\000\022\025\n\021CLIENT" +
      "_SESSION_ID\020\001\022\023\n\017CLIENT_LANGUAGE\020\002\022\026\n\022CL" +
      "IENT_SOCKET_TYPE\020\003\022\033\n\026CLIENT_REQUEST_REF" +
      "ERER\020\365\003\022\037\n\032CLIENT_REQUEST_SERVER_HOST\020\366\003" +
      "\022\037\n\032CLIENT_REQUEST_SERVER_PORT\020\367\003\022\023\n\016SER" +
      "VER_VERSION\020\351\007\022\020\n\013SERVER_HOST\020\352\007\022\020\n\013SERV" +
      "ER_PORT\020\353\007B\"\n\025com.akaxin.zaly.protoB\tCor" +
      "eProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_core_ErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_ErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_ErrorInfo_descriptor,
        new java.lang.String[] { "Code", "Info", });
    internal_static_core_TransportPackageData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_TransportPackageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_TransportPackageData_descriptor,
        new java.lang.String[] { "Header", "Body", "Err", });
    internal_static_core_TransportPackageData_HeaderEntry_descriptor =
      internal_static_core_TransportPackageData_descriptor.getNestedTypes().get(0);
    internal_static_core_TransportPackageData_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_TransportPackageData_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
